print("How old are you?", end='\n')
age = input()
print("How tall are you?", end=' ')
height = int(input())
print("How much do you weigh?", end=' ')
weight = input()
print(f"So, you're {age} years old, {height} inches tall and {weight} pounds heavy.")
